'use client';
import {useState} from 'react';
import {BookOpen,Layers,Trophy,ArrowUpRight,ArrowRight,ArrowLeft,ChevronRight,Check,CheckCircle2,Code2,GraduationCap,RotateCcw,Sparkles,Braces,Database,Box,Network,Zap,ShieldCheck,Timer,AlertCircle,LockKeyhole,Pause,Play} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {LabHero} from '@/components/lab-hero';
import {CodeBlock} from '@/components/code-block';
import data from '@/lib/content/study.json';
import type {Question} from '@/lib/quiz-core';
type Tab='simulado'|'flashcards'|'guia'|'ranking';
type PublicQuestion=Omit<Question,'answer'|'explanation'>;
type Exam={id:string;secret?:string;mode:'ranked'|'practice';nickname:string;questions:PublicQuestion[]};
type Result={score:number;total:number;review:(Question&{correct:boolean;selected:number})[];saved:boolean;mode:string};
type RankRow={nickname:string;score:number;finished_at:string};
const topicIcons=[Braces,Network,Zap,Database,Network,Box,ShieldCheck,Zap,Database,Box,Database];
const navItems=[{id:'simulado' as Tab,label:'Simulado',icon:GraduationCap},{id:'flashcards' as Tab,label:'Flashcards',icon:Layers},{id:'guia' as Tab,label:'Biblioteca',icon:BookOpen},{id:'ranking' as Tab,label:'Ranking',icon:Trophy}];
const topicShort=['Anotações','Arquitetura','IoC e DI','JPA','Relacionamentos','Records e DTOs','Validation','Kafka','Flyway','Docker','Redis'];
export default function Home(){
 const [motionPaused,setMotionPaused]=useState(false);
 const [tab,setTab]=useState<Tab>('simulado'),[nickname,setNickname]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [exam,setExam]=useState<Exam|null>(null),[answers,setAnswers]=useState<number[]>([]),[index,setIndex]=useState(0),[result,setResult]=useState<Result|null>(null);
 const [topic,setTopic]=useState('all'),[card,setCard]=useState(0),[flipped,setFlipped]=useState(false),[lesson,setLesson]=useState(0),[reviewed,setReviewed]=useState<number[]>([]);
 const [rows,setRows]=useState<RankRow[]>([]),[rankError,setRankError]=useState(''),[rankLoading,setRankLoading]=useState(false),[configured,setConfigured]=useState<boolean|null>(null);
 const cards=data.questions.filter(q=>topic==='all'||q.topic===Number(topic)),active=cards[card%cards.length];
 const current=exam?.questions[index],answered=answers.filter(a=>a>=0).length,l=data.lessons[lesson];
 const misses=result?.review.filter(q=>!q.correct)||[];
 async function rank(){setRankLoading(true);setRankError('');try{const r=await fetch('/api/ranking',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);setConfigured(d.configured);}catch(e){setRankError((e as Error).message);}finally{setRankLoading(false);}}
 function navigate(to:Tab){if(to==='ranking')void rank();setTab(to);setError('');window.scrollTo({top:0,behavior:'smooth'});}
 function openLesson(id:number){setLesson(id);navigate('guia');}
 async function start(){setBusy(true);setError('');try{const r=await fetch('/api/quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',nickname})});const d=await r.json();if(!r.ok)throw Error(d.error);setExam(d);setAnswers(Array(25).fill(-1));setIndex(0);setResult(null);window.scrollTo({top:0});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function finish(){if(!exam)return;setBusy(true);setError('');try{const r=await fetch('/api/quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'finish',id:exam.id,secret:exam.secret,mode:exam.mode,ids:exam.questions.map(q=>q.id),answers})});const d=await r.json();if(!r.ok)throw Error(d.error);setResult(d);window.scrollTo({top:0});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function moveCard(delta:number){setCard((card+cards.length+delta)%cards.length);setFlipped(false);}
 function newExam(){setExam(null);setResult(null);setError('');window.scrollTo({top:0});}
 return <div className="app-layout" data-motion={motionPaused?'paused':'playing'}>
 <aside className="sidebar"><button onClick={()=>navigate('simulado')} className="brand" aria-label="Spring Lab início"><span className="brand-mark"><Code2 size={25}/></span><span>spring<span className="brand-dot">.</span>lab<small>ESTUDO, NA PRÁTICA</small></span></button><p className="sidebar-label">APRENDER & PRATICAR</p><nav aria-label="Navegação principal">{navItems.map(n=><button key={n.id} aria-current={tab===n.id?'page':undefined} className={tab===n.id?'nav-item active':'nav-item'} onClick={()=>navigate(n.id)}><n.icon size={20}/><span>{n.label}</span>{n.id==='flashcards'&&<small>55</small>}{tab===n.id&&<ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-note"><span className="note-icon"><Sparkles size={19}/></span><strong>Seu caderno.<br/>Seu ritmo.</strong><p>Leia o código, formule sua resposta e só depois confira a explicação.</p><button onClick={()=>navigate('flashcards')}>Revisar agora<ArrowUpRight size={16}/></button></div><div className="sidebar-bottom"><div className="mini-spring">S</div><div>Preparação AV1<small>Spring Boot & ecossistema</small></div></div></aside>
 <div className="main-wrap"><header className="topbar"><span className="breadcrumb">Área de estudo <ChevronRight size={14}/><b>{navItems.find(n=>n.id===tab)?.label}</b></span><div className="topbar-tools"><button className="motion-toggle" onClick={()=>setMotionPaused(v=>!v)} aria-pressed={motionPaused} aria-label={motionPaused?'Ativar animações':'Pausar animações'}>{motionPaused?<Play size={14}/>:<Pause size={14}/>}<span>{motionPaused?'Ativar movimento':'Pausar movimento'}</span></button><span className="date-pill"><span/>AV1 · 18 SET</span></div></header>
 <main className={'content '+(tab==='simulado'&&!exam?'home-content':'')} id="conteudo"><div className="page-heading"><div><p className="eyebrow">{tab==='simulado'?'LABORATÓRIO / AV1':tab==='flashcards'?'REVISÃO ATIVA':tab==='guia'?'CADERNO DE CONSULTA':'PLACAR DA TURMA'}</p><h1>{tab==='simulado'?(result?'Vamos conferir?':exam?'Sua vez de resolver.':'Spring Lab — estudo na prática.'):tab==='flashcards'?'O que ficou na cabeça?':tab==='guia'?'Pode consultar.':'Quem já fez o simulado?'}</h1><p>{tab==='simulado'?'Leia, interprete e aplique os conceitos de Spring Boot.':tab==='flashcards'?'Pense na resposta. Revele a explicação. Repita o que precisar.':tab==='guia'?'11 assuntos, exemplos independentes e os detalhes que fazem diferença.':'Compare tentativas completas do mesmo simulado de 25 questões.'}</p></div><span className="heading-symbol">{tab==='simulado'?<GraduationCap/>:tab==='flashcards'?<Layers/>:tab==='guia'?<BookOpen/>:<Trophy/>}</span></div>
 {tab==='simulado'&&<>
 {!exam?<><div className="launch-grid"><section className="launch-feature"><LabHero onExplore={()=>navigate('guia')}/></section><section className="launch-config"><div className="exam-number"><strong>25</strong><span>questões<br/>por tentativa</span><span className="exam-orbit"><ArrowUpRight size={29}/></span></div><div className="config-divider"/><ul className="exam-rules"><li><CheckCircle2/>11 assuntos em cada prova</li><li><CheckCircle2/>55 questões no banco</li><li><CheckCircle2/>Gabarito comentado</li><li><Timer/>Sem pressa. Sem cronômetro.</li></ul><form onSubmit={e=>{e.preventDefault();void start();}}><label htmlFor="nickname">Seu nome no placar</label><input id="nickname" value={nickname} onChange={e=>setNickname(e.target.value)} minLength={2} maxLength={24} required placeholder="Seu apelido" autoComplete="nickname"/><p className="field-help">Use um apelido de 2 a 24 caracteres.</p><button className="btn primary full" disabled={busy||nickname.trim().length<2}>{busy?'Preparando questões…':'Começar simulado'}<ArrowRight size={18}/></button></form><p className="config-note">1 ponto por acerto · Você pode revisar antes de enviar.</p></section></div><div className="section-heading"><h2>O programa, sem enrolação.</h2><button className="text-btn" onClick={()=>navigate('guia')}>Ver conceitos<ArrowUpRight size={16}/></button></div><div className="topic-grid">{data.lessons.map(t=>{const Icon=topicIcons[t.id];return <button className="topic-card" key={t.id} onClick={()=>openLesson(t.id)}><span className={'topic-icon tone-'+t.id%4}><Icon size={19}/></span><span><small>MÓDULO {String(t.id+1).padStart(2,'0')}</small><b>{topicShort[t.id]}</b></span><ChevronRight size={15}/></button>})}</div></>:result?<>
 <section className="result-banner"><div className="score-ring" style={{background:`conic-gradient(#b8f577 ${result.score/result.total*360}deg,#365c50 0)`}}><div><strong>{result.score}</strong><span>de 25 acertos</span></div></div><div><p className="eyebrow">SIMULADO CONCLUÍDO</p><h2>{Math.round(result.score/25*100)}% de aproveitamento</h2><p>{result.saved?'Sua tentativa foi salva no ranking.': 'Treino concluído. Esta tentativa não entrou no ranking.'}</p><div className="actions"><button className="btn lime" onClick={newExam}>Novo desafio<RotateCcw size={17}/></button>{result.saved&&<button className="btn light-outline" onClick={()=>navigate('ranking')}>Ver ranking<Trophy size={17}/></button>}</div></div></section>
 <div className="section-heading"><h2>Onde você foi bem. Onde revisar.</h2><span>{misses.length===0?'Todos os conceitos em dia!':`${misses.length} questões para revisar`}</span></div><div className="performance-grid">{data.lessons.map(t=>{const qs=result.review.filter(q=>q.topic===t.id),hits=qs.filter(q=>q.correct).length;return <button key={t.id} className="performance-card" onClick={()=>openLesson(t.id)}><span>{topicShort[t.id]}<b>{hits}/{qs.length}</b></span><Progress value={hits/qs.length*100} aria-label={`${t.title}: ${hits} de ${qs.length}`}/><small>Revisar conceito<ArrowUpRight size={13}/></small></button>})}</div>
 <div className="section-heading"><h2>Entenda cada resposta</h2><span>Abra as questões para ver o raciocínio.</span></div><div className="review-list">{result.review.map((r,i)=><details className="review-item" key={r.id}><summary><span className={'review-state '+(r.correct?'correct':'incorrect')}>{r.correct?<Check size={17}/>:<RotateCcw size={15}/>}</span><span><small>{String(i+1).padStart(2,'0')} · {topicShort[r.topic]}</small><b>{r.prompt}</b></span><ChevronRight size={18}/></summary><div className="review-body">{r.code&&<CodeBlock code={r.code}/>}<p className={!r.correct?'wrong-answer':''}>Sua resposta: <b>{r.options[r.selected]}</b></p><p className="right-answer">Resposta correta: <b>{r.options[r.answer]}</b></p><div className="explanation"><Sparkles size={19}/><div><b>O raciocínio</b><p>{r.explanation}</p></div></div><button className="text-btn" onClick={()=>openLesson(r.topic)}>Estudar este conceito<ArrowRight size={16}/></button></div></details>)}</div></>:current?<>
 <div className="exam-bar"><span><b>{String(index+1).padStart(2,'0')}</b> / 25 questões</span><Progress value={answered/25*100} aria-label={`${answered} questões respondidas`}/><span>{answered} de 25 respondidas</span></div>
 {exam.mode==='practice'&&<div className="mode-note"><BookOpen size={16}/><span>Modo treino · Você receberá a correção completa, sem salvar no ranking.</span></div>}
 <section className="question-panel" key={current.id}><div className="question-heading"><div className="pills"><span className="pill green">{topicShort[current.topic]}</span><span className="pill">{current.kind}</span><span className="pill">{current.difficulty}</span></div><h2>{current.prompt}</h2></div><div className={current.code?'question-layout with-code':'question-layout'}>{current.code&&<CodeBlock code={current.code} label={current.topic===9||current.code.startsWith('spring:')?'CONFIGURAÇÃO':'JAVA / SQL'}/>}<div><p className="answer-instruction">SELECIONE UMA ALTERNATIVA</p><RadioGroup value={answers[index]<0?'':String(answers[index])} onValueChange={v=>setAnswers(a=>a.map((old,i)=>i===index?Number(v):old))} aria-label="Alternativas">{current.options.map((option,i)=><label key={i} className={'answer-option '+(answers[index]===i?'selected':'')}><RadioGroupItem value={String(i)} aria-label={option}/><span className="answer-letter">{String.fromCharCode(65+i)}</span><span>{option}</span>{answers[index]===i&&<Check size={18}/>}</label>)}</RadioGroup></div></div><div className="question-controls"><button className="btn secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft size={17}/>Anterior</button><span>Você pode mudar de ideia antes de finalizar.</span>{index<24?<button className="btn primary" onClick={()=>setIndex(i=>i+1)}>Próxima questão<ArrowRight size={17}/></button>:<button className="btn primary" disabled={busy||answered!==25} onClick={finish}>{busy?'Corrigindo…':'Finalizar simulado'}<CheckCircle2 size={17}/></button>}</div></section>
 <section className="question-map"><div><h3>Seu percurso</h3><p>{answered===25?'Tudo respondido. Você já pode finalizar.':'Toque em um número para voltar a uma questão.'}</p></div><div className="question-numbers">{exam.questions.map((q,i)=><button key={q.id} aria-label={`Questão ${i+1}${answers[i]>=0?', respondida':''}`} aria-current={index===i?'step':undefined} className={(answers[i]>=0?'done ':'')+(index===i?'current':'')} onClick={()=>setIndex(i)}>{i+1}</button>)}</div>{answered===25&&index<24&&<button className="text-btn" disabled={busy} onClick={finish}>Finalizar e ver correção<ArrowRight size={16}/></button>}</section><p className="footnote">As respostas ficam nesta sessão. Trocar de seção mantém o progresso; recarregar a página reinicia a tentativa em andamento.</p></>:null}
 {error&&<p className="error" role="alert"><AlertCircle size={18}/>{error}</p>}
 </>}
 {tab==='flashcards'&&<><div className="flash-toolbar"><span><Layers size={18}/><b>{cards.length} cartões</b><span className="muted">· {reviewed.filter(id=>cards.some(c=>c.id===id)).length} revisados nesta sessão</span></span><Select value={topic} onValueChange={v=>{setTopic(v);setCard(0);setFlipped(false);}}><SelectTrigger className="topic-select" aria-label="Filtrar assunto"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os assuntos</SelectItem>{data.lessons.map(l=><SelectItem key={l.id} value={String(l.id)}>{l.title}</SelectItem>)}</SelectContent></Select></div><section className={'flash-stage '+(flipped?'revealed':'')}><div className="flash-meta"><span className="pill green">{topicShort[active.topic]}</span><span>{String(card%cards.length+1).padStart(2,'0')} / {cards.length}</span></div><div className="flash-content" key={`${active.id}-${flipped}`}><span className="flash-side">{flipped?'RESPOSTA & RACIOCÍNIO':'PENSE ANTES DE REVELAR'}</span><h2>{flipped?active.options[active.answer]:active.prompt}</h2>{flipped?<div className="flash-explanation"><Sparkles size={22}/><p>{active.explanation}</p></div>:active.code?<CodeBlock code={active.code}/>:<p className="muted">Tente explicar em voz alta, sem consultar as alternativas.</p>}</div><button className={'btn '+(flipped?'secondary':'primary')} onClick={()=>setFlipped(v=>!v)}><RotateCcw size={17}/>{flipped?'Voltar à pergunta':'Revelar resposta'}</button></section><div className="flash-controls"><button className="btn secondary" onClick={()=>moveCard(-1)}><ArrowLeft size={17}/>Anterior</button>{flipped&&<button className="btn primary" onClick={()=>{setReviewed(ids=>ids.includes(active.id)?ids:[...ids,active.id]);moveCard(1);}}>Entendi, próximo<Check size={17}/></button>}<button className="btn secondary" onClick={()=>moveCard(1)}>Próximo<ArrowRight size={17}/></button></div><div className="study-tip"><span><Sparkles size={20}/></span><p><b>Um jeito de saber se entendeu:</b> Antes de avançar, diga por que a resposta faz sentido. Os cartões revisados são marcados apenas nesta sessão.</p></div></>}
 {tab==='guia'&&<><div className="library-layout"><nav className="module-nav" aria-label="Assuntos da biblioteca"><span className="eyebrow">OS 11 FUNDAMENTOS</span>{data.lessons.map(t=><button key={t.id} aria-current={lesson===t.id?'page':undefined} className={lesson===t.id?'active':''} onClick={()=>setLesson(t.id)}><span>{String(t.id+1).padStart(2,'0')}</span>{topicShort[t.id]}{lesson===t.id&&<ChevronRight size={14}/>}</button>)}</nav><article className="lesson"><div className="lesson-header"><span className="pill green">MÓDULO {String(lesson+1).padStart(2,'0')}</span><BookOpen size={25}/></div><h2>{l.title}</h2><p className="lesson-lead">{l.summary}</p><div className="lesson-text">{l.body.map((p,i)=><p key={i}>{p}</p>)}</div><h3><Code2 size={21}/>Veja na prática</h3><CodeBlock code={l.code} label={lesson===9?'DOCKER COMPOSE':'EXEMPLO DIDÁTICO'}/><div className="attention"><AlertCircle size={21}/><div><b>Vale prestar atenção</b><p>{l.pitfall}</p></div></div><div className="lesson-footer"><span>Pronto para testar esse conceito?</span><button className="btn primary" onClick={()=>{setTopic(String(l.id));setCard(0);setFlipped(false);navigate('flashcards');}}>Abrir flashcards<ArrowRight size={17}/></button></div></article></div><details className="sources"><summary>Referências oficiais e origem dos conteúdos<ChevronRight size={16}/></summary><p>Os temas foram alinhados à lista da AV1 e às tecnologias presentes no delivery_app_2026. Os exemplos e perguntas são independentes do projeto, para testar entendimento dos conceitos.</p><div>{data.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={14}/></a>)}</div></details></>}
 {tab==='ranking'&&<><section className="ranking-heading"><span className="trophy-icon"><Trophy size={32}/></span><div><h2>Ranking de tentativas</h2><p>1 ponto por acerto. Em empate, a tentativa concluída antes fica acima.</p></div><button className="btn secondary" disabled={rankLoading} onClick={rank}><RotateCcw size={16}/>Atualizar</button></section><section className="ranking-panel">{rankLoading?<div className="empty" role="status"><span className="spinner"/><h3>Buscando resultados…</h3></div>:rankError?<div className="empty error" role="alert"><AlertCircle/><p>{rankError}</p><button className="btn secondary" onClick={rank}>Tentar novamente</button></div>:configured===false?<div className="empty"><span className="empty-icon"><LockKeyhole size={32}/></span><h3>O ranking está aguardando ativação.</h3><p>Por enquanto, pratique à vontade: o simulado e a correção funcionam normalmente. O ranking compartilhado ficará disponível quando o banco for conectado.</p><button className="btn primary" onClick={()=>navigate('simulado')}>Praticar agora<ArrowRight size={17}/></button></div>:rows.length===0?<div className="empty"><span className="empty-icon"><Trophy size={34}/></span><h3>O primeiro lugar está esperando.</h3><p>Conclua uma tentativa de 25 questões para inaugurar o ranking.</p><button className="btn primary" onClick={()=>navigate('simulado')}>Começar desafio<ArrowRight size={17}/></button></div>:<Table><TableHeader><TableRow><TableHead>POSIÇÃO</TableHead><TableHead>PARTICIPANTE</TableHead><TableHead>ACERTOS</TableHead><TableHead>CONCLUÍDO EM</TableHead></TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}><TableCell><span className={'rank-place place-'+i}>{i===0?<Trophy size={19}/>:String(i+1).padStart(2,'0')}</span></TableCell><TableCell><span className="rank-name"><span className="avatar">{r.nickname.slice(0,1).toUpperCase()}</span>{r.nickname}</span></TableCell><TableCell><span className="rank-score">{r.score}<small>/ 25</small></span></TableCell><TableCell>{new Date(r.finished_at).toLocaleString('pt-BR')}</TableCell></TableRow>)}</TableBody></Table>}</section><p className="footnote">Ranking informal de estudo, com as 50 melhores tentativas. Apelidos não verificam identidade. Novas tentativas aparecem separadamente.</p></>}
 <footer className="footer"><span><span className="footer-dot"/>SPRING LAB</span><span>Feito para ler código, errar e entender.</span><span>AV1 / 2026</span></footer>
 </main></div></div>
}
